sudo: false
language: node_js
node_js:
  - 9.8.0

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH=$HOME/.yarn/bin:$PATH

script:
- yarn build
- yarn test

after_success:
- yarn send-coverage


cache:
  yarn: false
  directories:
    - node_modules
