
<a href="https://npmjs.org/package/{{ config.npm }}" rel="nofollow"><img alt="View on npm" src="https://img.shields.io/npm/v/{{ config.npm }}.svg" style="max-width:100%;"></a>
&nbsp;
<a href="https://npmjs.org/package/{{ config.npm }}" rel="nofollow"><img alt="npm downloads" src="https://img.shields.io/npm/dm/{{ config.npm }}.svg" style="max-width:100%;"></a>

<br />
<br />

<a href="https://david-dm.org/{{ config.github }}" rel="nofollow"><img alt="Dependencies" src="https://img.shields.io/david/{{ config.github }}.svg" style="max-width:100%;"></a>
&nbsp;
<a href="https://travis-ci.org/{{ config.github }}" rel="nofollow"><img alt="Build Status" src="https://travis-ci.org/{{ config.github }}.svg?branch=master" style="max-width:100%;"></a>
&nbsp;
<a href="https://codecov.io/gh/{{ config.github }}" rel="nofollow"><img alt="codecov" src="https://codecov.io/gh/{{ config.github }}/branch/master/graph/badge.svg" style="max-width:100%;"></a>
&nbsp;
<a href="https://nodesecurity.io/{{ config.nodesecurity }}" rel="nofollow"><img alt="NSP Status" src="https://nodesecurity.io/{{ config.nodesecurity }}/badge" style="max-width:100%;"></a>
