<a href="https://npmjs.org/package/{{ config.npm }}" rel="nofollow"><img alt="View on npm" src="https://img.shields.io/npm/v/{{ config.npm }}.svg" style="max-width:100%;"></a>
&nbsp;
<a href="https://npmjs.org/package/{{ config.npm }}" rel="nofollow"><img alt="npm downloads" src="https://img.shields.io/npm/dm/{{ config.npm }}.svg" style="max-width:100%;"></a>
&nbsp;
<a href="https://travis-ci.org/{{ config.github }}" rel="nofollow"><img alt="Build Status" src="https://travis-ci.org/{{ config.github }}.svg?branch=master" style="max-width:100%;"></a>

&nbsp;
<a class="github-button" href="https://github.com/{{ config.github }}" data-icon="octicon-star" data-show-count="true" aria-label="Star {{ config.github }} on GitHub">Star</a>
<script async defer src="https://buttons.github.io/buttons.js"></script>
